version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: passwd
      POSTGRES_USER: django
      POSTGRES_PASSWORD: bestsyncframe
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db
volumes:
  postgres_data: